CREATE PROCEDURE PRCOURSELIST  
(
     @FLDCOURSEID			BIGINT = NULL        
    ,@FLDCOURSENAME			NVARCHAR(MAX) = NULL
    ,@FLDDURATIONMONTH		INT = NULL      
    ,@ROWUSERCODE			INT = NULL            
)
AS
BEGIN
    SET NOCOUNT ON;
    
    SELECT 
          FLDCOURSEID
        , FLDCOURSENAME
        , FLDDURATIONMONTH
    FROM TBLCOURSE WITH (NOLOCK) 
    WHERE (@FLDCOURSEID IS NULL OR FLDCOURSEID = @FLDCOURSEID)  
             AND (@FLDCOURSENAME IS NULL OR FLDCOURSENAME LIKE '%' + @FLDCOURSENAME + '%') 
              AND (@FLDDURATIONMONTH IS NULL OR FLDDURATIONMONTH = @FLDDURATIONMONTH) 
    ORDER BY 
        FLDCOURSEID; 
        
END











