

CREATE PROCEDURE PRCOURSESEARCH
(
      @FLDCOURSENAME			VARCHAR(MAX)	= NULL
    , @FLDDURATIONMONTH			DECIMAL(10,2)	= NULL
    , @SORTBY		        	VARCHAR(100)	= NULL
	, @SORTDIRECTION	        TINYINT			= NULL
	, @PAGENUMBER		        INT
	, @PAGESIZE			        INT
	, @RESULTCOUNT		        INT OUTPUT
	, @TOTALPAGECOUNT       	INT OUTPUT 
	 
)

AS
BEGIN
SET NOCOUNT ON; ----COUNT ALL RECORD

		DECLARE @ROWFROM    BIGINT
		DECLARE @ROWTO		BIGINT

		DECLARE @TEMPTABLE TABLE
		(
		 FLDCOURSEID		INT
		,FLDROWNUMBER	    BIGINT IDENTITY (1,1)
		)


		SET @SORTDIRECTION = ISNULL(@SORTDIRECTION , 0)

		IF(@SORTDIRECTION = 0)
		BEGIN
		     INSERT INTO @TEMPTABLE
			 SELECT FLDCOURSEID
			 FROM TBLCOURSE (NOLOCK)
			 WHERE (FLDCOURSENAME  LIKE '%'+ @FLDCOURSENAME + '%' OR @FLDCOURSENAME IS NULL )
			 AND   (FLDDURATIONMONTH LIKE '%'+ @FLDDURATIONMONTH +'%' OR @FLDDURATIONMONTH IS NULL )
			 ORDER BY FLDCOURSENAME

			 			 
			SET @RESULTCOUNT	= @@ROWCOUNT
			SET @TOTALPAGECOUNT = DBO.FNTOTALPAGECOUNT(@RESULTCOUNT,@PAGESIZE)
			SET @ROWFROM		= DBO.FNROWFROM(@PAGENUMBER,@PAGESIZE)
			SET @ROWTO			= DBO.FNROWTO(@PAGENUMBER,@PAGESIZE)


			END

			IF(@SORTDIRECTION = 1)
			BEGIN
			      INSERT INTO @TEMPTABLE
				  SELECT FLDCOURSEID
				  FROM TBLCOURSE (NOLOCK)
				  WHERE ( FLDCOURSENAME   LIKE '%'+ @FLDCOURSENAME +'%' OR @FLDCOURSENAME IS NULL  )
				  AND   ( FLDDURATIONMONTH LIKE '%'+ @FLDDURATIONMONTH +'%' OR @FLDDURATIONMONTH IS NULL )
				  ORDER BY FLDCOURSENAME DESC


				SET @RESULTCOUNT	= @@ROWCOUNT
				SET @TOTALPAGECOUNT = DBO.FNTOTALPAGECOUNT(@RESULTCOUNT,@PAGESIZE)
				SET @ROWFROM		= DBO.FNROWFROM(@PAGENUMBER,@PAGESIZE)
				SET @ROWTO			= DBO.FNROWTO(@PAGENUMBER,@PAGESIZE)

            END

			SELECT c.FLDCOURSEID
			,c.FLDCOURSENAME
			,c.FLDDURATIONMONTH
			,c.FLDDTKEY
			FROM @TEMPTABLE T
					INNER JOIN TBLCOURSE C (NOLOCK)
						 ON T.FLDCOURSEID=C.FLDCOURSEID
			 WHERE T.FLDROWNUMBER BETWEEN @ROWFROM AND @ROWTO

END




